Fix/spatial for merge
ecolabdata/ckanext-ecospheres pull request #11
Opened 2022-12-12 14:09 UTC by asboukerram

2022-12-13 14:01 UTC, alhyss commented
Merci @asboukerram 

Quelques remarques/questions.

### Gestion des connexions à la base

J'aurais aimé que le module `parser.model` reste indépendant de l'environnement CKAN. Son rôle est de définir la structure de données, pas de gérer les connexions à la base. J'ai en outre besoin d'utiliser ce module hors de CKAN pour des tâches d'administration.

Est-ce qu'il y aurait un inconvénient à créer l'objet `sqlalchemy.Engine` dans le module `loader` ? Mais y en a-t-il seulement besoin ? Le gestionnaire de contexte [`Session`](https://github.com/ecolabdata/ckanext-ecospheres/blob/f7a177f6c5aaa8393ab29004497422355274d7f7/ckanext/ecospheres/vocabulary/loader.py#L45) crée déjà implicitement un objet `sqlalchemy.Engine` lorsqu'il est appelé par [`__create_table_and_load_data`](https://github.com/ecolabdata/ckanext-ecospheres/blob/f7a177f6c5aaa8393ab29004497422355274d7f7/ckanext/ecospheres/vocabulary/loader.py#L162). À quoi sert-il d'en avoir un autre ?

L'une des opérations ajoutée à `parser.model` est la mise en relation des objets `sqlalchemy.MetaData` et `sqlalchemy.Engine` via `sqlalchemy.MetaData.bind`. Mais c'est un mécanisme obsolète qui ne sera plus pris en charge dans les prochaines versions de `sqlalchemy` et je n'ai pas l'impression que le reste du code en tirait partie de toute façon ?

Bref, j'ai l'impression qu'aucune des modifications de l'en-tête de `parser.model` ne se justifie vraiment ?

Par ailleurs, je ne comprends pas très bien pourquoi `loader` redéfinit `SQL_METADATA` et `SQL_SCHEMA`. `SQL_SCHEMA` devrait être importé depuis `parser.model`. En théorie, il devrait en aller de même de `SQL_METADATA`, mais je ne crois pas qu'il y ait lieu d'avoir un objet `sqlalchemy.MetaData` dans `loader` à ce stade ?

### Configuration des clés étrangères

Je ne comprends pas les paramètres `initially=True` ajoutés à la définition des clés étrangères dans `model`. 

Par exemple : 
```python
            sqlalchemy.ForeignKeyConstraint(
                columns=['uri'],
                refcolumns=[f'{self.label.name}.uri'],
                ondelete='CASCADE',
                onupdate='CASCADE',
                initially=True
            )
```

Normalement il ne devrait pas y avoir besoin de retarder la validation des contraintes. La table des labels est la première de la liste et c'est elle qui est référencée par toutes les clés étrangères. S'il y a un problème (est-ce le cas ?) alors il faudrait plutôt que je corrige de mon côté.

En outre, je n'ai pas pris le temps de tester (désolée pour ça), mais je ne vois pas ce qu'on obtient avec cette syntaxe pour `initially`. Si on voulait que les clés étrangères soient créées avec `DEFERRABLE INITIALLY DEFERRED`, ne faudrait-il pas plutôt écrire ce qui suit ? Dans tous les autres cas, la contrainte est vérifiée immédiatement, me semble-t-il.
```python
            sqlalchemy.ForeignKeyConstraint(
                columns=['uri'],
                refcolumns=[f'{self.label.name}.uri'],
                ondelete='CASCADE',
                onupdate='CASCADE',
                deferrable=True,
                initially='DEFERRED'
            )
```

À toute fin utile : [doc de SQLAlchemy](https://docs.sqlalchemy.org/en/14/core/constraints.html#sqlalchemy.schema.ForeignKey) et [doc de PostgreSQL](https://www.postgresql.org/docs/14/sql-createtable.html) pour les commandes de création de contraintes de clés étrangères.

### Nettoyage du code

Serait-il possible de retirer du module `loader` toutes les fonctions, commandes d'import, etc. qui ne servent plus ?

### Prise en charge des erreurs lors de la récupération/normalisation des vocabulaires

Comme expliqué en détails dans le [premier message](https://github.com/ecolabdata/ckanext-ecospheres/issues/1#issue-1441957182) de l'issue #1 (partie _Gestion des erreurs_), il est nécessaire d'analyser le résultat de `VocabularyIndex.load` avant d'essayer de mettre en base le vocabulaire contenu dans l'attribut `data`.

D'une part parce qu'il est essentiel d'alerter l'administrateur sur le fait que sa commande de mise à jour du vocabulaire n'a pas eu le résultat escompté, pour lui permettre de prendre les mesures qui s'imposent (y compris pour les erreurs non critiques). D'autre part parce que ceci échoue lorsqu'il y a eu une erreur critique lors de l'acquisition du vocabulaire, car `data` vaut alors `None` :

```python
vocab_data=VocabularyIndex.load(name).data
for table_name, table in vocab_data.items():
```

2022-12-16 15:54 UTC, streino commented on README.md
> +        POST /api/load-vocabs
Le endpoint est `/api/load-vocab` au singulier

2022-12-19 15:00 UTC, alhyss requested changes
Pour plus d'explications sur les remarques et suggestions de ma review, cf. ma réponse au pull request. À noter que je n'ai pas regardé en détails la partie API. De ce côté je pense qu'on peut faire le merge puis faire les corrections, pour pouvoir tester également sur ECO.

2022-12-19 15:00 UTC, alhyss commented on ckanext/ecospheres/vocabulary/loader.py
>                  logging.info(f"Insetion des données dans la table {table_name}")
```suggestion
                logger.debug(f"Insertion des données dans la table {table_name}")
```

2022-12-19 15:00 UTC, alhyss commented on ckanext/ecospheres/vocabulary/parser/model.py
> +
inutile
```suggestion

```

2022-12-19 15:00 UTC, alhyss commented on ckanext/ecospheres/vocabulary/parser/model.py
> +
inutile
```suggestion

```

2022-12-19 15:00 UTC, alhyss commented on README.md
> +        POST /api/load-vocabs
Dans ce cas : 
```suggestion
        POST /api/load-vocab
```

2022-12-19 15:17 UTC, alhyss commented on ckanext/ecospheres/vocabulary/loader.py
>                  logging.error(f"Erreur lors de la création du table {table_name}\t {str(e)}")
À faire post-merge.

2022-12-19 15:20 UTC, alhyss commented on ckanext/ecospheres/vocabulary/loader.py
>                  logging.info(f"Insetion des données dans la table {table_name}")
À faire post-merge.

2022-12-19 15:39 UTC, merged